#
## train_osegnet_wildlife.py
#
#
#  This script trains the custom O-SegNet architecture on the wildlife domain using the pseudo-label masks generated by the pre-trained YOLOv8-seg model.
#  It defines a custom Dataset class to stream both the raw images and their corresponding pseudo masks directly from disk, ensuring that the training 
#  loop is optimized for GPU acceleration. The model is trained using a standard cross-entropy loss function, and the final weights are saved 
#  for later evaluation and comparison against the YOLOv8-seg baseline.
#
#
#

import os
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
from pathlib import Path
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from tqdm import tqdm
from models import OSegNet #Custom O-SegNet architecture 


BATCH_SIZE = 32  # Maximizes the RTX 2080's VRAM capability
LEARNING_RATE = 2e-4
EPOCHS = 5
NUM_WORKERS = 4  # Utilizes 4 CPU threads to decode images ahead of the GPU

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

PSEUDO_TRAIN_MANIFEST = Path("/home/greatgilbertsoco/WolfDetect/data/pseudo_final_train_manifest.csv")
MASK_DIR = Path("/home/greatgilbertsoco/WolfDetect/data/pseudo_masks")
IWILDCAM_RAW_DIR = Path("/home/greatgilbertsoco/WolfDetect/data/train_images")
IDAHO_RAW_DIR = Path("/home/greatgilbertsoco/WolfDetect/data/wolf_images")
WEIGHTS_SAVE_PATH = "/home/greatgilbertsoco/WolfDetect/code/osegnet_weights.pth"

class CustomWildlifeSegmentationDataset(Dataset):
    """Custom Dataset to stream raw images and their corresponding pseudo-label masks for O-SegNet training."""
    def __init__(self, manifest_path):
        self.df = pd.read_csv(manifest_path)
        self.img_transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])
        
    def __len__(self):
        return len(self.df)
        
    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        file_name = row['file_name']
        source = row['dataset_source']
        mask_name = row['pseudo_mask_name']
        
        # Stream Image
        base_dir = IWILDCAM_RAW_DIR if source == 'iwildcam' else IDAHO_RAW_DIR
        img_path = base_dir / file_name
        try:
            with Image.open(img_path).convert('RGB') as img:
                img_tensor = self.img_transform(img)
        except Exception:
            img_tensor = torch.zeros((3, 224, 224))
            
        # Stream Pre-computed Pseudo Mask Matrix
        mask_path = MASK_DIR / mask_name
        try:
            mask_array = np.load(mask_path).astype(np.int64)
            mask_tensor = torch.from_numpy(mask_array)
        except Exception:
            mask_tensor = torch.zeros((224, 224), dtype=torch.long)
        
        return img_tensor, mask_tensor

def train_wildlife_domain():
    print("=====================================================================")
    print("        O-SEGNET WILDLIFE HARDWARE-ACCELERATED TRAINING LOOP         ")
    print("=====================================================================")
    print(f"[Hardware Target] ACTIVE ACCELERATOR: {DEVICE}")
    print(f"[Hardware Target] COMPUTE UNIT: {torch.cuda.get_device_name(0)}")


    #Clear GPU memory and set PyTorch CUDA allocator to use expandable segments for better fragmentation handling
    torch.cuda.empty_cache()
    os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
    
    dataset = CustomWildlifeSegmentationDataset(PSEUDO_TRAIN_MANIFEST)
    
    # Critical GPU Tuning parameters
    loader = DataLoader(
        dataset, 
        batch_size=BATCH_SIZE, 
        shuffle=True, 
        num_workers=NUM_WORKERS, 
        pin_memory=True,
        drop_last=True
    )
    
    model = OSegNet(num_classes=2).to(DEVICE)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
    
    # Run cuDNN architectural search space auto-tuner
    torch.backends.cudnn.benchmark = True
    
    for epoch in range(1, EPOCHS + 1):
        model.train()
        running_loss = 0.0
        
        progress_bar = tqdm(loader, desc=f"Epoch {epoch}/{EPOCHS}")
        for images, targets in progress_bar:

            # non_blocking=True makes data pipeline uploads fully asynchronous
            images = images.to(DEVICE, non_blocking=True)
            targets = targets.to(DEVICE, non_blocking=True)
            
            optimizer.zero_grad()
            outputs = model(images)
            
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()
            
            running_loss += loss.item()
            progress_bar.set_postfix({'Loss': f"{loss.item():.4f}"})
            
        print(f"[Epoch Summary] Epoch {epoch} completed. Average Loss: {running_loss / len(loader):.4f}")
        
    torch.save(model.state_dict(), WEIGHTS_SAVE_PATH)
    print(f"\n[Success] Domain-adapted weights exported safely to: {WEIGHTS_SAVE_PATH}")

if __name__ == "__main__":
    train_wildlife_domain()